
## Configure DNS only *after* Windows Server DNS nameserver (Role) is configured

# Until Windows Server or other provider/manager of DNS/DHCP is configured, 
# Windows host (Hyper-V) will report VM interface IP of "169.254.x.x"
# 
# 169.254.x.x addresses are of the APIPA (Automatic Private IP Addressing) range, 
# which Windows and other OS assign when a device fails to get IP address from DHCP server.
# 
# - Hyper-V VMs reporting 169.254.x.x addresses 
#   suggest they are not receiving an IP address from DHCP server.
# - RHEL VM reporting only "lo" interface 
#   suggests it's not connected to any virtual switch.

if (-not "$NatAlias") { . .\network-define.ps1 }

## Configure DNS servers for each adapter : We're using mixed pairs
$NatDNS = "$NatNtwk.2" # Internal (NAT1 subnet) resolver is Windows Server DNS nameserver (Role)
$ExtDNS = "$ExtNtwk.1"  # External (Internet) resolver is Gateway Router
$PubDNS = "8.8.8.8"       # Any public (Internet) DNS nameserver; 
# 8.8.8.8 (Google), 9.9.9.9 (QuadNine), 1.1.1.1 (CloudFlare), ...

## Set DNS servers for Internal Adapter
Set-DnsClientServerAddress -InterfaceAlias "$NatAlias" -ServerAddresses @("$NatDNS", "$ExtDNS")

## Set DNS servers for External Adapter
Set-DnsClientServerAddress -InterfaceAlias "$ExtAlias" -ServerAddresses @("$ExtDNS", "$PubDNS")

## Disable DHCP : Allow Windows Server to manage exclusively
Set-NetIPInterface -InterfaceAlias "$NatAlias" -AddressFamily IPv4 -Dhcp Disabled
#Set-NetIPInterface -InterfaceAlias "$NatAlias" -AddressFamily IPv6 -Dhcp Disabled

## Set domain suffixes that are appended to unqualified hostnames during DNS queries
## Adding to NAT conn provides resolution of unqualified hostnames from both NAT and WSL subnets
Set-DnsClient -InterfaceAlias "$NatAlias" -ConnectionSpecificSuffix "$NatDomain"

# Set the metric : lower metric has higher priority
Set-NetIPInterface -InterfaceAlias "$ExtAlias" -InterfaceMetric 10
Set-NetIPInterface -InterfaceAlias "$NatAlias" -InterfaceMetric 15
Set-NetIPInterface -InterfaceAlias "$WslAlias" -InterfaceMetric 20

Get-DnsClientServerAddress `
    | Select-Object InterfaceAlias, AddressFamily, ServerAddresses `
    | Where-Object { $_.ServerAddresses -ne "" }

Get-DnsClient | Select-Object InterfaceAlias, ConnectionSpecificSuffix

## DNS @ WSL2 network is best handled automatically, 
## which auto-generates /etc/resolv.conf
## The nameserver is set to WSL's virtual DNS server (10.255.255.254)
## And it sets the default search domain for unqualified dowmain names:
##
# ☩ cat /etc/resolv.conf
# # This file was automatically generated by WSL. To stop automatic generation of this file, add the following entry to /etc/wsl.conf:
# # [network]
# # generateResolvConf = false
# nameserver 10.255.255.254
# search SEMPERLAN lime.lan hsd1.md.comcast.net